/* tslint:disable */
/* eslint-disable */
/**
 * Ezer LaChayim API
 * Redis' social hackathon June 2023 - bridge between volunteers and those in need of rides to the hospital 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Car
 */
export interface Car {
    /**
     * 
     * @type {number}
     * @memberof Car
     */
    carId?: number;
    /**
     * 
     * @type {string}
     * @memberof Car
     */
    brand?: string;
    /**
     * 
     * @type {string}
     * @memberof Car
     */
    model?: string;
    /**
     * 
     * @type {string}
     * @memberof Car
     */
    color?: string;
    /**
     * 
     * @type {number}
     * @memberof Car
     */
    passengerSeatsCount?: number;
}
