/* tslint:disable */
/* eslint-disable */
/**
 * Ezer LaChayim API
 * Redis' social hackathon June 2023 - bridge between volunteers and those in need of rides to the hospital 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Patient } from './patient';
import { User } from './user';
/**
 * 
 * @export
 * @interface RideRequester
 */
export interface RideRequester extends User {
    /**
     * 
     * @type {string}
     * @memberof RideRequester
     */
    passengerCellPhone?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof RideRequester
     */
    specialRequest?: Array<RideRequesterSpecialRequestEnum>;
    /**
     * 
     * @type {string}
     * @memberof RideRequester
     */
    servicePeriod?: RideRequesterServicePeriodEnum;
    /**
     * 
     * @type {Patient}
     * @memberof RideRequester
     */
    patient?: Patient;
}

/**
    * @export
    * @enum {string}
    */
export enum RideRequesterSpecialRequestEnum {
    WheelChair = 'WheelChair',
    WheelChairStorage = 'WheelChairStorage',
    BabyChair = 'BabyChair',
    KidsChair = 'KidsChair',
    AccessibleCar = 'AccessibleCar',
    PatientDelivery = 'PatientDelivery'
}
/**
    * @export
    * @enum {string}
    */
export enum RideRequesterServicePeriodEnum {
    Week = 'Week',
    TwoWeeks = 'TwoWeeks',
    Month = 'Month',
    More = 'More'
}

