/* tslint:disable */
/* eslint-disable */
/**
 * Ezer LaChayim API
 * Redis' social hackathon June 2023 - bridge between volunteers and those in need of rides to the hospital 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { User } from './user';
/**
 * 
 * @export
 * @interface Driver
 */
export interface Driver extends User {
    /**
     * 
     * @type {string}
     * @memberof Driver
     */
    license?: string;
    /**
     * 
     * @type {string}
     * @memberof Driver
     */
    licenseExpiryDate?: string;
}


