/* tslint:disable */
/* eslint-disable */
/**
 * Ezer LaChayim API
 * Redis' social hackathon June 2023 - bridge between volunteers and those in need of rides to the hospital 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * 
     * @type {string}
     * @memberof User
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    authProvider?: UserAuthProviderEnum;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    /**
     * 
     * @type {string}
     * @memberof User
     */
    role?: UserRoleEnum;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    cellPhone?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    registrationState?: UserRegistrationStateEnum;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    city?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    address?: string;
    isInitialPassword:boolean;
}

/**
    * @export
    * @enum {string}
    */
export enum UserAuthProviderEnum {
    Email = 'Email',
    Google = 'Google',
    Apple = 'Apple'
}
/**
    * @export
    * @enum {string}
    */
export enum UserRoleEnum {
    Requester = 'Requester',
    Driver = 'Driver',
    Admin = 'Admin'
}
/**
    * @export
    * @enum {string}
    */
export enum UserRegistrationStateEnum {
    Pending = 'Pending',
    Approved = 'Approved',
    Rejected = 'Rejected'
}

